openapi: "3.0.0"
info:
  description: "This is the Configuration API for UC4."
  version: "0.13.1"
  title: "UC4"

servers:
  - url: https://uc4.cs.upb.de/api/production/configuration-management

tags:
- name: "Version Management"
  description: "Everything about the Version"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"
- name: "Configuration Management"
  description: "Everything about the configuration"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/upb-uc4"

paths:
  /version:
    get:
      tags:
      - "Version Management"
      summary: "Get version"
      description: "Returns the version of the current service"
      operationId: "getVersion"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonServiceVersion'
  /version/hyperledger:
    get:
      tags:
      - "Version Management"
      summary: "Get versions of the hyperledger api, chaincode and network"
      description: "Get versions of the hyperledger api, chaincode and network of the underlying hyperledger fabric network"
      operationId: "getVersionHyperledger"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HyperledgerVersions'
              examples:
                ExampleHyperledgerVersions:
                  $ref: '#/components/examples/ExampleHyperledgerVersions'
                ExampleHyperledgerVersionsUnavailabe:
                  $ref: '#/components/examples/ExampleHyperledgerVersionsUnavailable'
  /configuration:
    get:
      tags:
      - "Configuration Management"
      summary: "Get the current Configuration"
      description: "Fetch the current Configuration of the system"
      operationId: "getConfiguration"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
              examples:
                ConfigurationExample:
                  $ref: '#/components/examples/ExampleConfiguration'
  /semester:
    get:
      tags:
      - "Configuration Management"
      summary: "Get the semester of the given date"
      description: "Get which semester corresponds to the given date"
      operationId: "getSemester"
      parameters:
      - name: "date"
        in: "query"
        description: "Date for which the semester needs to be fetched"
        required: false
        schema:
          type: 'string'
          example: 
            date: "2019-09-02"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonSemester'
              examples:
                ConfigurationExample:
                  $ref: '#/components/examples/JsonSemester'
        "400":
          description: | 
            Bad Request  
            types: QueryParameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedError'
  /validation:
    get:
      tags:
      - "Configuration Management"
      summary: "Get the regular expressions used for validation"
      description: "Fetch the regular expressions and the corresponding error message used in the validaiton of various objects"
      operationId: "getValidation"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationConfiguration'
components:
  securitySchemes:
    uc4_token_login:
      type: apiKey
      in: cookie
      name: login
    uc4_token_login_header:
      type: http
      scheme: bearer
  schemas:
    Configuration:
      type: "object"
      properties:
        countries:
          type: array
          items:
            type: string
        languages:
          type: array
          items:
            type: string
        courseTypes:
          type: array
          items:
            type: string
    ValidationConfiguration:
      type: "object"
      properties:
        authenticationUser:
          type: object
          properties:
            username:
              $ref: '#/components/schemas/ValidationPair'
            password:
              $ref: '#/components/schemas/ValidationPair'
        postMessageCSR:
          type: object
          properties:
            certificateSigningRequest:
              $ref: '#/components/schemas/ValidationPair'
        course:
          type: "object"
          properties:
            courseName:
              $ref: '#/components/schemas/ValidationPair'
            startDate:
              $ref: '#/components/schemas/ValidationPair'
            endDate:
              $ref: '#/components/schemas/ValidationPair'
            ects:
              $ref: '#/components/schemas/ValidationPair'
            lecturerId:
              $ref: '#/components/schemas/ValidationPair'
            maxParticipants:
              $ref: '#/components/schemas/ValidationPair'
            courseDescription:
              $ref: '#/components/schemas/ValidationPair'
        user:
          type: "object"
          properties:
            username:
              $ref: '#/components/schemas/ValidationPair'
            firstName:
              $ref: '#/components/schemas/ValidationPair'
            lastName:
              $ref: '#/components/schemas/ValidationPair'
            email:
              $ref: '#/components/schemas/ValidationPair'
            phoneNumber:
              $ref: '#/components/schemas/ValidationPair'
            birthDate:
              $ref: '#/components/schemas/ValidationPair'
        lecturer:
          type: "object"
          properties:
            freeText:
              $ref: '#/components/schemas/ValidationPair'
            researchArea:
              $ref: '#/components/schemas/ValidationPair'
        address:
          type: "object"
          properties:
            street:
              $ref: '#/components/schemas/ValidationPair'
            houseNumber:
              $ref: '#/components/schemas/ValidationPair'
            city:
              $ref: '#/components/schemas/ValidationPair'
    ValidationPair:
      type: "object"
      properties:
        regex:
          type: string
        message:
          type: string
    HyperledgerVersions:
      type: "object"
      properties:
        apiVersion:
          type: string
        chaincodeVersion:
          type: string
        networkVersion:
          type: string
    JsonSemester:
      type: object
      properties:
        semester:
          type: string
    JsonServiceVersion:
      type: object
      properties:
        serviceVersion:
          type: string
    GenericError:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/GenericError'
        - type: object
    DetailedError:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/upb-uc4/api/develop/errors.yaml#/components/schemas/DetailedError'
        - type: object
  examples:
    ExampleHyperledgerVersions:
      summary: "An example for the HyperledgerVersions object"
      value:
        apiVersion: "v0.10.0"
        chaincodeVersion: "v0.10.0"
        networkVersion: "v0.10.0"
    ExampleHyperledgerVersionsUnavailable:
      summary: "An example for the HyperledgerVersions object, with an unavailable version"
      value:
        apiVersion: "v0.10.0"
        chaincodeVersion: "v0.10.0"
        networkVersion: null
    ExampleConfiguration:
      summary: "An example for the configuration"
      value:
        countries: ["Germany", "United States", "Italy", "France", "United Kingdom", "Belgium", "Netherlands", "Spain", "Austria", "Switzerland", "Poland"]
        languages: ["German", "English"]
        courseTypes: ["Lecture", "Seminar", "Project Group"]
    JsonSemester:
      summary: "An example for the JsonSemester"
      value:
        semester: "SS2020"
        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io" 
